sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable
before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
script:
  - |
    cargo build --verbose &&
    cargo test &&
    travis-cargo --only stable doc
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
after_success:
  - |
    travis-cargo --only stable doc-upload &&
    travis-cargo --only stable coveralls --no-sudo
env:
  global:
    secure: JLBlgHY6OEmhJ8woewNJHmuBokTNUv7/WvLkJGV8xk0t6bXBwSU0jNloXwlH7FiQTc4TccX0PumPDD4MrMgxIAVFPmmmlQOCmdpYP4tqZJ8xo189E5zk8lKF5OyaVYCs5SMmFC3cxCsKjfwGIexNu3ck5Uhwe9jI0tqgkgM3URA=
